### ISSUE TITLE
Treatment assignment over time

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalDataSummaries#5]
We need [Portal_plots.csv](https://github.com/weecology/PortalData/blob/master/SiteandMethods/Portal_plots.csv) to get the correct assignment of treatment type over time. The assignments are only by year at this point. Is there any way to get them to month?

**Comment by skmorgane** [comment]
I think I found the info we need. Are we thinking of modifying Portal_plots.csv so that it becomes Year,month,plot,treatment ?

**Comment by gmyenni** [comment]
Yeah, that's what I was thinking.

**Comment by skmorgane** [comment]
ok, I have added new code (Add_months_PortalPlots.R) to PortalDataSummaries. It takes the original Portal_plots.csv file and uses that info to create a bigger month level file and fills it in with treatment data based on the best info I can find. Sources for the dates are included in the file. The only treatment flip I could not nail down to month is the switch of the spectab plots to controls in the early 2000s. Do we have notes on that somewhere? If so, we can tweak that code with the actual date. The new .csv is in the Rodent folder. I gave it a different name (new_Portal_plots.csv) because I didn't want to break any scripts currently using Portal_plots.csv. To rerun this code, though,we currently need the current (non-monthly) Portal_plots.csv, but we can rewrite Add_months_PortalPlots so that it does not need it if we want to get rid of the old file.

**Comment by gmyenni** [comment]
Should we move this to PortalData/DataCleaningScripts? I think it makes sense to, ultimately, just have this code in the cleaning scripts to document how we created it (and to add new months in the future) and have Portal_plots.csv in SiteandMethods. Also, do we need the other columns besides yr, mo, plot, and treatment?
